all:
	${CXX} -Wall -o solution solution.cpp ${CXXFLAGS}
	${CXX} -Wall -o tl_solution tl_solution.cpp ${CXXFLAGS}
	${CXX} -Wall -o ok_rand_solution ok_rand_solution.cpp ${CXXFLAGS}

clean:
	rm solution
